[package]
name = "my_man"
version = "0.4.0"
authors = ["Isaac M. Good <imgood@imgoodproductions.org>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "*"
log = "*"
metrics = "*"
futures = "*"
async-trait = "*"
songbird = "0.2"
mockall = "*"
tempfile = "*"

[dependencies.tokio]
version = "*"
features = ["macros", "rt-multi-thread"]

[dependencies.serenity]
version = "0.10"
features = [
   "cache", 
   "unstable_discord_api",
   "voice",
   "rustls_backend"
]
