[package]
name = "my_man"
version = "0.3.0"
authors = ["Isaac M. Good <imgood@imgoodproductions.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "*"
log = "*"
metrics = "*"
futures = "*"
async-trait = "*"
songbird = "0.2"

[dependencies.tokio]
version = "*"
features = ["macros", "rt-multi-thread"]

[dependencies.serenity]
version = "0.10"
features = [
   "cache",
   "client",
   "framework",
   "standard_framework",
   "unstable_discord_api",
   "voice",
   "http",
   "rustls_backend"
]
