[package]
name = "my_man"
version = "0.3.0"
authors = ["Isaac M. Good <imgood@imgoodproductions.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "*"
log = "*"
metrics = "*"
futures = "*"
async-trait = "*"
tokio = "*"

[dependencies.serenity]
version = "0.9"
features = ["cache", "framework", "standard_framework", "voice", "http", "rustls_backend"]
