name: Deploy to Container

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Cache registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache build artifacts
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --release
    - name: Test
      run: cargo test
    - name: Upload result
      uses: actions/upload-artifact@v1
      with:
        name: release
        path: target/release/my_man
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Download release binary
        uses: actions/download-artifact@v1
        with:
          name: release
      - name: Deploy
        run: cp release/my_man ~/ && chmod +x ~/my_man
      - name: Install Dependent Packages
        run: apt-get update && apt-get --assume-yes install ffmpeg curl
      - name: Install Youtube DL
        run: >
          youtube-dl --update
          || wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl
          && chmod a+rx /usr/local/bin/youtube-dl
      - name: Activate
        run: systemctl restart soundboard
