name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Build
      env:
        SODIUM_LIB_DIR: /usr/lib64
        SODIUM_SHARED: 1
      run: cargo build --release
    - name: Run tests
      env:
        SODIUM_LIB_DIR: /usr/lib64
        SODIUM_SHARED: 1
      run: cargo test
    - name: Upload result
      uses: actions/upload-artifact@v1
      with:
        name: release
        path: target/release/my_man
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Download release binary
        uses: actions/download-artifact@v1
        with:
          name: release
      - name: Deploy
        run: cp release/my_man ~/
      - name: Activate
        run: systemctl restart soundboard
