name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build
      env: { SODIUM_LIB_DIR: /usr/lib64, SODIUM_SHARED: 1 }
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose
    - name: Activate
      run: systemctl restart soundboard
