name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: my-man

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose
    - name: Activate
      run: systemctl restart soundboard
