name: Deploy to Container

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build
      run: cargo build --release
    - name: Test
      run: cargo test
    - name: Upload result
      uses: actions/upload-artifact@v1
      with:
        name: release
        path: target/release/my_man
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Download release binary
        uses: actions/download-artifact@v1
        with:
          name: release
      - name: Deploy
        run: cp release/my_man ~/ && chmod +x ~/my_man
      - name: Activate
        run: systemctl restart soundboard
